"""Gate G2 checks for INGEST-002 -> validation/ingestion/g2-check.md (exit 1 on any failure).

1. A fresh run of each arm gives the same chunk IDs and content hashes as the committed chunk file.
2. Every chunk ID matches `{source_id}:{chunker_config}:{index:04d}`, contiguous from 0000 per document.
3. Every Arm A heading path exists in the EPIC-01 section inventory (same source_id).
4. For every chunk of both arms, normalized_text[char_start:char_end] == display_text.
5. Arm A: no chunk is longer than max_chars; both arms emit the same field set.
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "scripts" / "ingestion"))

from build_chunks import CHUNKS_DIR, CONFIG, NORMALIZED, build  # noqa: E402

INVENTORY = PROJECT_ROOT / "data" / "processed" / "documents" / "section-inventory.jsonl"
REPORT = PROJECT_ROOT / "validation" / "ingestion" / "g2-check.md"


def _read_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line]


def main() -> int:
    config = json.loads(CONFIG.read_text(encoding="utf-8"))["arms"]
    texts = {record["id"]: record["text"] for record in _read_jsonl(NORMALIZED)}
    inventory = {(row["source_id"], row["heading_path"]) for row in _read_jsonl(INVENTORY)}
    results: list[tuple[str, bool, str]] = []
    field_sets = {}
    for arm in ("A", "B"):
        committed = _read_jsonl(CHUNKS_DIR / f"arm-{arm.lower()}.jsonl")
        fresh, _ = build(arm)
        second, _ = build(arm)
        key = [(r["chunk_id"], r["content_hash"]) for r in committed]
        same = key == [(r["chunk_id"], r["content_hash"]) for r in fresh] == [
            (r["chunk_id"], r["content_hash"]) for r in second
        ]
        results.append((f"Arm {arm}: two fresh runs == committed file (IDs + hashes, {len(key)} chunks)", same, ""))

        name = config[arm]["chunker_config"]
        pattern = re.compile(rf"^(\d{{2}}):{re.escape(name)}:(\d{{4}})$")
        per_doc = defaultdict(list)
        malformed = []
        for record in committed:
            match = pattern.match(record["chunk_id"])
            if not match or match.group(1) != record["source_id"]:
                malformed.append(record["chunk_id"])
            else:
                per_doc[match.group(1)].append(int(match.group(2)))
        gaps = [doc for doc, indexes in per_doc.items() if indexes != list(range(len(indexes)))]
        detail = f"malformed: {malformed[:5]}; non-contiguous docs: {gaps}" if malformed or gaps else ""
        results.append((f"Arm {arm}: ID format `{{source_id}}:{name}:{{index:04d}}`, contiguous per doc", not detail, detail))

        mismatched = [
            r["chunk_id"] for r in committed if texts[r["source_id"]][r["char_start"] : r["char_end"]] != r["display_text"]
        ]
        results.append(
            (f"Arm {arm}: normalized_text[char_start:char_end] == display_text", not mismatched, ", ".join(mismatched[:5]))
        )
        results.append((f"Arm {arm}: all 24 documents chunked", len(per_doc) == 24 == len(texts), f"{len(per_doc)} docs"))
        field_sets[arm] = {tuple(record) for record in committed}

        if arm == "A":
            missing = sorted({(r["source_id"], r["heading_path"]) for r in committed} - inventory)
            results.append(
                ("Arm A: every heading path is in the section inventory", not missing, "; ".join(map(str, missing[:5])))
            )
            maximum = config["A"]["max_chars"]
            too_long = [r["chunk_id"] for r in committed if len(r["display_text"]) > maximum]
            results.append((f"Arm A: no chunk longer than {maximum} chars", not too_long, ", ".join(too_long[:5])))

    same_fields = len(field_sets["A"] | field_sets["B"]) == 1
    results.append(("Both arms: identical field set on every record", same_fields, str(field_sets["A"] | field_sets["B"])))

    lines = [
        "# G2 check (INGEST-002)",
        "",
        "Generated by `scripts/ingestion/check_g2.py` (no timestamps; re-running on unchanged inputs gives this file).",
        "",
        "| Check | Result | Detail |",
        "|---|---|---|",
    ]
    lines += [f"| {name} | {'PASS' if ok else 'FAIL'} | {detail.replace('|', '/')} |" for name, ok, detail in results]
    passed = all(ok for _, ok, _ in results)
    lines += ["", f"**Overall: {'PASS' if passed else 'FAIL'}** ({sum(ok for _, ok, _ in results)}/{len(results)})", ""]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("\n".join(lines))
    return 0 if passed else 1


if __name__ == "__main__":
    sys.exit(main())
