"""Blueprint coverage check for Arm A (INGEST-004, ADR-0003 D3a) -> validation/ingestion/blueprint-coverage-arm-a.md.

    python scripts/ingestion/check_blueprint_coverage.py [--chunks PATH] [--no-write]

For every expected and alternate (source_id, heading_path) in data/evaluation/questions/blueprint.yaml, count the
Arm A chunks whose char span overlaps a span of that section (any variant, ADR-0003 D8). A section with 0
overlapping chunks cannot be a section hit in Arm A. Exit 1 when any path has 0 chunks or is not a section.
"""
import argparse
import json
import sys
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "scripts" / "ingestion"))

from build_chunks import CHUNKS_DIR, NORMALIZED  # noqa: E402

sys.path.insert(0, str(PROJECT_ROOT / "src"))
from knowledge_assistant.application.ingestion.build_chunks import load_normalized_documents  # noqa: E402
from knowledge_assistant.core.models import HEADING_PATH_SEPARATOR  # noqa: E402

BLUEPRINT = PROJECT_ROOT / "data" / "evaluation" / "questions" / "blueprint.yaml"
REPORT = PROJECT_ROOT / "validation" / "ingestion" / "blueprint-coverage-arm-a.md"


def _targets(blueprint: dict) -> list[tuple[str, str, str, str]]:
    """(blueprint id, kind, source_id, heading_path) for every expected and alternate source, in file order."""
    rows = []
    for entry in blueprint["blueprints"]:
        for kind, field in (("expected", "expected_sources"), ("alternate", "acceptable_alternate_sources")):
            for source in entry.get(field) or []:
                rows.append((entry["id"], kind, str(source["source_id"]), source["heading_path"]))
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--chunks", type=Path, default=CHUNKS_DIR / "arm-a.jsonl")
    parser.add_argument("--no-write", action="store_true", help="print only; do not write the report")
    args = parser.parse_args()

    documents = {document.source_id: document for document in load_normalized_documents(NORMALIZED)}
    chunks = [json.loads(line) for line in args.chunks.read_text(encoding="utf-8").splitlines() if line]
    targets = _targets(yaml.safe_load(BLUEPRINT.read_text(encoding="utf-8")))

    counts: dict[tuple[str, str], int | None] = {}
    for _, _, source_id, path in targets:
        if (source_id, path) in counts:
            continue
        spans = [
            (section.char_start, section.char_end)
            for section in documents[source_id].sections
            if HEADING_PATH_SEPARATOR.join(section.heading_path) == path
        ]
        counts[(source_id, path)] = (
            sum(
                any(start < chunk["char_end"] and chunk["char_start"] < end for start, end in spans)
                for chunk in chunks
                if chunk["source_id"] == source_id
            )
            if spans
            else None
        )

    failing = [(s, p) for (s, p), n in counts.items() if not n]
    lines = [
        "# Blueprint coverage, Arm A (INGEST-004)",
        "",
        "Generated by `scripts/ingestion/check_blueprint_coverage.py` (no timestamps). Chunks overlapping each expected",
        "and alternate section span of `blueprint.yaml` (any variant). 0 = the section can never be an Arm A section hit.",
        "",
        f"Chunk file: `{args.chunks.resolve().relative_to(PROJECT_ROOT).as_posix() if args.chunks.resolve().is_relative_to(PROJECT_ROOT) else args.chunks.name}`",
        "",
        "| Blueprint | Kind | Source | Heading path | Overlapping chunks |",
        "|---|---|---|---|---|",
    ]
    for blueprint_id, kind, source_id, path in targets:
        count = counts[(source_id, path)]
        shown = "not a section" if count is None else str(count)
        lines.append(f"| {blueprint_id} | {kind} | {source_id} | {path.replace('|', '/')} | {shown} |")
    lines += [
        "",
        f"Distinct (source, heading path) pairs: {len(counts)}; with 0 overlapping chunks or not a section: {len(failing)}",
        "",
        f"**Overall: {'FAIL' if failing else 'PASS'}**" + (f" ({'; '.join(f'#{s} {p}' for s, p in failing)})" if failing else ""),
        "",
    ]
    if not args.no_write:
        REPORT.parent.mkdir(parents=True, exist_ok=True)
        REPORT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("\n".join(lines[-4:]))
    return 1 if failing else 0


if __name__ == "__main__":
    sys.exit(main())
